version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5001:5000
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      QUART_ENV: development
    user: ${CURRENT_UID}
    entrypoint: ["python3", "runserver.py"]

  mysql:
    image: mariadb
    volumes:
      - .:/app
      - open_booking_connect_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: connect

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8083:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_HOST: mysql

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:latest

volumes:
  open_booking_connect_mysql:
